on: workflow_dispatch

name: R-CMD-check-with-valgrind

jobs:
  R-CMD-check-with-valgrind:
    timeout-minutes: 90
    
    runs-on: ubuntu-latest

    name: ubuntu-latest (release) w/ valgrind

    strategy:
      fail-fast: false

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      ## R CMD check
      _R_CHECK_CRAN_INCOMING_: false
      _R_CHECK_MATRIX_DATA_: true
      ## Specific to package
      _R_CHECK_USE_VALGRIND_: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Install system dependencies
        run: |
          sudo apt-get install --yes valgrind

      - name: Session info
        run: |
          options(width = 100)
          capabilities()
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
          ## Verify LANGUAGE settings by generating a translatable error
          cat(sprintf("LANGUAGE=%s\n", sQuote(Sys.getenv("LANGUAGE"))))
          cat(sprintf("locales: %s\n", sQuote(Sys.getlocale())))
          tryCatch(log("a"), error = conditionMessage)
        shell: Rscript {0}

      - name: Check with valgrind
        run: |
          rcmdcheck::rcmdcheck(
            build_args = "--no-build-vignettes",
            args = c("--use-valgrind", "--no-codoc", "--no-examples",
                     "--no-manual", "--ignore-vignettes"),
            error_on = "warning",
            check_dir = "check"
          )
        shell: Rscript {0}
        
      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-rrelease-results
          path: check
